# Generated by Django 4.0.3 on 2022-03-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mountain', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('mountain_name', models.CharField(default='', max_length=20)),
                ('content', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('hiking_img', models.ImageField(upload_to='post/post_upload_images/')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_mt_ref', to='mountain.mountain')),
                ('user', models.ForeignKey(db_column='author_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_post_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mooyaho_post',
            },
        ),
    ]
