# Generated by Django 4.0.3 on 2022-03-23 04:25

from django.db import migrations, models
import post.post_models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_hiking_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hiking_img',
            field=models.ImageField(upload_to=post.post_models.hiking_img_upload_path),
        ),
    ]
