# Generated by Django 4.0.3 on 2022-03-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_hiking_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
