# Generated by Django 4.0.3 on 2022-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mountain_id', models.FloatField(blank=True, null=True)),
                ('mountain_name', models.CharField(blank=True, max_length=30, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('selection_reason', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('course_information', models.TextField(blank=True, null=True)),
                ('mountain_information', models.TextField(blank=True, null=True)),
                ('stay', models.TextField(blank=True, null=True)),
                ('transportation', models.TextField(blank=True, null=True)),
                ('local_code', models.FloatField(blank=True, null=True)),
                ('local_name', models.TextField(blank=True, null=True)),
                ('maxy', models.FloatField(blank=True, null=True)),
                ('maxx', models.FloatField(blank=True, null=True)),
                ('miny', models.FloatField(blank=True, null=True)),
                ('minx', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mountain',
                'managed': True,
            },
        ),
    ]
