# Generated by Django 4.0.3 on 2022-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
