# Generated by Django 4.0.3 on 2022-04-05 12:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.user_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mountain', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MooyahoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('gender', models.CharField(choices=[('0', '남'), ('1', '여')], max_length=2, verbose_name='성별')),
                ('age_gr', models.CharField(choices=[('0', '10대'), ('1', '20대'), ('2', '30대'), ('3', '40대'), ('4', '50대'), ('5', '60대'), ('6', '70대 이상')], max_length=10, verbose_name='연령대')),
                ('disabled', models.BooleanField(default=False, verbose_name='탈퇴 여부')),
                ('superuser', models.BooleanField(default=False, verbose_name='관리자 여부')),
                ('profile_img', models.ImageField(blank=True, default='images/no-img.png', upload_to=user.user_models.profile_img_upload_path, verbose_name='프로필 사진')),
                ('exp', models.CharField(choices=[('0', '초급'), ('1', '중급'), ('2', '고급')], max_length=10, verbose_name='등산 경력')),
                ('reason', models.CharField(choices=[('0', '친목모임'), ('1', '건강관리'), ('2', '탐험'), ('3', '친환경'), ('4', '취미'), ('5', '사진')], max_length=100, verbose_name='등산 목적')),
                ('latitude', models.FloatField(default=0, verbose_name='유저 위치 위도')),
                ('longitude', models.FloatField(default=0, verbose_name='유저 위치 경도')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'mooyaho_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_mountain_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mountain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mountain.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userviewlog',
            },
        ),
    ]
