# Generated by Django 4.0.3 on 2022-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mooyahouser',
            name='disabled_reason',
            field=models.TextField(default='', verbose_name='탈퇴 사유'),
        ),
    ]
